In [1]:
import numpy as np

In [2]:
from numpy import genfromtxt

In [3]:
data = genfromtxt('/Users/hafsatariq/Downloads/Computer-Vision-with-Python/DATA/bank_note_data.txt', delimiter = ',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:,4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = labels

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [32]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [42]:
from sklearn.preprocessing import MinMaxScaler

In [43]:
scaler_object = MinMaxScaler()

In [45]:
scaler_object.fit(X_train)

MinMaxScaler()

In [46]:
scaled_X_train = scaler_object.transform(X_train)

In [47]:
scaled_X_test = scaler_object.transform(X_test)

In [48]:
scaled_X_train.max()

1.0000000000000002

In [52]:
scaled_X_train.min()

0.0

In [55]:
from keras.models import Sequential
from keras.layers import Dense

In [56]:
model = Sequential()

In [57]:
model.add(Dense(4,input_dim = 4, activation = 'relu'))

In [58]:
model.add(Dense(8,activation = 'relu'))

In [59]:
model.add(Dense(1,activation = 'relu'))

In [63]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [64]:
model.fit(scaled_X_train, y_train, epochs = 50, verbose = 2)

Epoch 1/50
29/29 - 0s - loss: 2.1354 - accuracy: 0.5495


2025-01-20 12:49:02.547472: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2025-01-20 12:49:02.552012: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


Epoch 2/50
29/29 - 0s - loss: 1.5814 - accuracy: 0.5495
Epoch 3/50
29/29 - 0s - loss: 1.3711 - accuracy: 0.5495
Epoch 4/50
29/29 - 0s - loss: 1.1944 - accuracy: 0.5495
Epoch 5/50
29/29 - 0s - loss: 1.0629 - accuracy: 0.5495
Epoch 6/50
29/29 - 0s - loss: 0.9527 - accuracy: 0.5495
Epoch 7/50
29/29 - 0s - loss: 0.8616 - accuracy: 0.5495
Epoch 8/50
29/29 - 0s - loss: 0.7897 - accuracy: 0.5495
Epoch 9/50
29/29 - 0s - loss: 0.7369 - accuracy: 0.5495
Epoch 10/50
29/29 - 0s - loss: 0.6973 - accuracy: 0.5495
Epoch 11/50
29/29 - 0s - loss: 0.6699 - accuracy: 0.5691
Epoch 12/50
29/29 - 0s - loss: 0.6501 - accuracy: 0.6115
Epoch 13/50
29/29 - 0s - loss: 0.6375 - accuracy: 0.6551
Epoch 14/50
29/29 - 0s - loss: 0.6286 - accuracy: 0.6942
Epoch 15/50
29/29 - 0s - loss: 0.6217 - accuracy: 0.7193
Epoch 16/50
29/29 - 0s - loss: 0.6157 - accuracy: 0.7236
Epoch 17/50
29/29 - 0s - loss: 0.6107 - accuracy: 0.7203
Epoch 18/50
29/29 - 0s - loss: 0.6056 - accuracy: 0.7225
Epoch 19/50
29/29 - 0s - loss: 0.6002 -

In [69]:
model.metrics_names

['loss', 'accuracy']

In [70]:
from sklearn.metrics import confusion_matrix, classification_report

In [77]:
predictions = model.predict(scaled_X_test)

In [80]:
predicted_labels = (predictions > 0.5).astype("int32")

In [81]:
print(classification_report(y_test, predicted_labels))

              precision    recall  f1-score   support

         0.0       0.86      0.96      0.91       257
         1.0       0.95      0.79      0.86       196

    accuracy                           0.89       453
   macro avg       0.90      0.88      0.88       453
weighted avg       0.90      0.89      0.89       453

